services:
  shorturl:
    image: hn275/shorturl
    container_name: "shorturl-app"
    environment:
      - PORT=3000

  nginx:
    image: nginx
    container_name: "shorturl-nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/:/etc/nginx/
    links:
      - "shorturl:app"
